apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: kaustubhbiswas/node-app:v3
          volumeMounts:
          - mountPath: /data
            name: node-app-storage
          ports:
            - containerPort: 3000
          envFrom: 
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
      volumes:
        - name: node-app-storage
          persistentVolumeClaim:
            claimName: node-app-pvc        