name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and push the Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/node-app:${{ github.sha }}

    - name: Trigger Deploy Workflow
    - uses: peter-evans/workflow-dispatch@v1
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: deploy-to-k8s

